######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 22 19:30:21 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h qgraphics.h startwindow.h
SOURCES += mainwindow.cpp qtgame.cpp startwindow.cpp
