#############################################################################
# Makefile for building: game_elvisxu
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri Apr 26 21:43:09 2013
# Project:  game_elvisxu.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile game_elvisxu.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = asteroid.cpp \
		background.cpp \
		bomb.cpp \
		boss.cpp \
		enemy.cpp \
		laser.cpp \
		life.cpp \
		mainwindow.cpp \
		qgraphics.cpp \
		qtgame.cpp \
		shiplife.cpp \
		spaceship.cpp \
		startwindow.cpp moc_mainwindow.cpp \
		moc_qgraphics.cpp \
		moc_startwindow.cpp
OBJECTS       = asteroid.o \
		background.o \
		bomb.o \
		boss.o \
		enemy.o \
		laser.o \
		life.o \
		mainwindow.o \
		qgraphics.o \
		qtgame.o \
		shiplife.o \
		spaceship.o \
		startwindow.o \
		moc_mainwindow.o \
		moc_qgraphics.o \
		moc_startwindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		game_elvisxu.pro
QMAKE_TARGET  = game_elvisxu
DESTDIR       = 
TARGET        = game_elvisxu

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: game_elvisxu.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile game_elvisxu.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile game_elvisxu.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/game_elvisxu1.0.0 || $(MKDIR) .tmp/game_elvisxu1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/game_elvisxu1.0.0/ && $(COPY_FILE) --parents asteroid.h background.h bomb.h boss.h enemy.h laser.h life.h mainwindow.h qgraphics.h shiplife.h spaceship.h startwindow.h thing.h .tmp/game_elvisxu1.0.0/ && $(COPY_FILE) --parents asteroid.cpp background.cpp bomb.cpp boss.cpp enemy.cpp laser.cpp life.cpp mainwindow.cpp qgraphics.cpp qtgame.cpp shiplife.cpp spaceship.cpp startwindow.cpp .tmp/game_elvisxu1.0.0/ && (cd `dirname .tmp/game_elvisxu1.0.0` && $(TAR) game_elvisxu1.0.0.tar game_elvisxu1.0.0 && $(COMPRESS) game_elvisxu1.0.0.tar) && $(MOVE) `dirname .tmp/game_elvisxu1.0.0`/game_elvisxu1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/game_elvisxu1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qgraphics.cpp moc_startwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qgraphics.cpp moc_startwindow.cpp
moc_mainwindow.cpp: startwindow.h \
		qgraphics.h \
		enemy.h \
		thing.h \
		spaceship.h \
		asteroid.h \
		laser.h \
		boss.h \
		bomb.h \
		background.h \
		shiplife.h \
		life.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_qgraphics.cpp: enemy.h \
		thing.h \
		spaceship.h \
		asteroid.h \
		laser.h \
		boss.h \
		bomb.h \
		background.h \
		shiplife.h \
		life.h \
		qgraphics.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qgraphics.h -o moc_qgraphics.cpp

moc_startwindow.cpp: startwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) startwindow.h -o moc_startwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

asteroid.o: asteroid.cpp asteroid.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o asteroid.o asteroid.cpp

background.o: background.cpp background.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o background.o background.cpp

bomb.o: bomb.cpp bomb.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bomb.o bomb.cpp

boss.o: boss.cpp boss.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boss.o boss.cpp

enemy.o: enemy.cpp enemy.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enemy.o enemy.cpp

laser.o: laser.cpp laser.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o laser.o laser.cpp

life.o: life.cpp life.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o life.o life.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		startwindow.h \
		qgraphics.h \
		enemy.h \
		thing.h \
		spaceship.h \
		asteroid.h \
		laser.h \
		boss.h \
		bomb.h \
		background.h \
		shiplife.h \
		life.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qgraphics.o: qgraphics.cpp qgraphics.h \
		enemy.h \
		thing.h \
		spaceship.h \
		asteroid.h \
		laser.h \
		boss.h \
		bomb.h \
		background.h \
		shiplife.h \
		life.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qgraphics.o qgraphics.cpp

qtgame.o: qtgame.cpp mainwindow.h \
		startwindow.h \
		qgraphics.h \
		enemy.h \
		thing.h \
		spaceship.h \
		asteroid.h \
		laser.h \
		boss.h \
		bomb.h \
		background.h \
		shiplife.h \
		life.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtgame.o qtgame.cpp

shiplife.o: shiplife.cpp shiplife.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shiplife.o shiplife.cpp

spaceship.o: spaceship.cpp spaceship.h \
		thing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spaceship.o spaceship.cpp

startwindow.o: startwindow.cpp startwindow.h \
		mainwindow.h \
		qgraphics.h \
		enemy.h \
		thing.h \
		spaceship.h \
		asteroid.h \
		laser.h \
		boss.h \
		bomb.h \
		background.h \
		shiplife.h \
		life.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o startwindow.o startwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qgraphics.o: moc_qgraphics.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qgraphics.o moc_qgraphics.cpp

moc_startwindow.o: moc_startwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_startwindow.o moc_startwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

